//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIIOT.Trical.EbigWeChat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsPacketService", Namespace="http://www.ebigcn.com")]
    [System.SerializableAttribute()]
    public partial class wsPacketService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ebigcn.com", ConfigurationName="EbigWeChat.EbeitXmlWebService")]
    public interface EbeitXmlWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ebigcn.com/EbeitXmlWebService/normalServiceRequest", ReplyAction="http://www.ebigcn.com/EbeitXmlWebService/normalServiceResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string normalService(string spid, string username, string password, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ebigcn.com/EbeitXmlWebService/normalServiceRequest", ReplyAction="http://www.ebigcn.com/EbeitXmlWebService/normalServiceResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> normalServiceAsync(string spid, string username, string password, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ebigcn.com/EbeitXmlWebService/setWSPacketServiceRequest", ReplyAction="http://www.ebigcn.com/EbeitXmlWebService/setWSPacketServiceResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        void setWSPacketService(MIIOT.Trical.EbigWeChat.wsPacketService arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ebigcn.com/EbeitXmlWebService/setWSPacketServiceRequest", ReplyAction="http://www.ebigcn.com/EbeitXmlWebService/setWSPacketServiceResponse")]
        System.Threading.Tasks.Task setWSPacketServiceAsync(MIIOT.Trical.EbigWeChat.wsPacketService arg0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EbeitXmlWebServiceChannel : MIIOT.Trical.EbigWeChat.EbeitXmlWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EbeitXmlWebServiceClient : System.ServiceModel.ClientBase<MIIOT.Trical.EbigWeChat.EbeitXmlWebService>, MIIOT.Trical.EbigWeChat.EbeitXmlWebService {
        
        public EbeitXmlWebServiceClient() {
        }
        
        public EbeitXmlWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EbeitXmlWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbeitXmlWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbeitXmlWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string normalService(string spid, string username, string password, string xml) {
            return base.Channel.normalService(spid, username, password, xml);
        }
        
        public System.Threading.Tasks.Task<string> normalServiceAsync(string spid, string username, string password, string xml) {
            return base.Channel.normalServiceAsync(spid, username, password, xml);
        }
        
        public void setWSPacketService(MIIOT.Trical.EbigWeChat.wsPacketService arg0) {
            base.Channel.setWSPacketService(arg0);
        }
        
        public System.Threading.Tasks.Task setWSPacketServiceAsync(MIIOT.Trical.EbigWeChat.wsPacketService arg0) {
            return base.Channel.setWSPacketServiceAsync(arg0);
        }
    }
}
